# MIT License
#
# Copyright (c) 2017 appPlant
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation tasks (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

FROM centos:6
MAINTAINER Sebastian Katzer "katzer@appplant.de"

# libs
RUN yum  -y update && yum -y install epel-release centos-release-scl && yum -y install \
            bison \
            clang \
            curl \
            devtoolset-4-binutils \
            devtoolset-4-gcc \
            git \
            # glibc-devel.i686 \
            # libgcc.i686 \
            openssh-clients \
            openssh-server \
            tar && \
    yum  -y clean all
RUN mkdir -p /usr/lib/gcc/x86_64-redhat-linux && \
    rm -rf /usr/lib/gcc/x86_64-redhat-linux/4.4.4 && \
    ln -s /opt/rh/devtoolset-4/root/usr/lib/gcc/x86_64-redhat-linux/5.3.1 /usr/lib/gcc/x86_64-redhat-linux/4.4.4
ENV PATH /opt/rh/devtoolset-4/root/usr/bin:$PATH

# ruby
RUN cd /tmp && curl -s http://cache.ruby-lang.org/pub/ruby/2.5/ruby-2.5.1.tar.gz -s -o - | tar zxf - && cd /tmp/ruby-2.5.1 && \
    ./configure --prefix=/opt/ruby --disable-install-doc && \
    make && make install && \
    echo "gem: --no-document" > ~/.gemrc && \
    rm -rf /tmp/*
ENV PATH /opt/ruby/bin:$PATH

# sshd
RUN    mkdir -p $HOME/.ssh \
    && service sshd start \
    && ssh-keygen -t rsa -q -f $HOME/.ssh/dev.key -N "" \
    && echo `cat $HOME/.ssh/dev.key.pub` >> $HOME/.ssh/authorized_keys \
    && ssh-keygen -t rsa -q -f $HOME/.ssh/devp.key -N "phrase" \
    && echo `cat $HOME/.ssh/devp.key.pub` >> $HOME/.ssh/authorized_keys \
    && ssh-keyscan -t rsa localhost >> $HOME/.ssh/known_hosts \
    && echo $'service sshd start' > $HOME/.sshdrc \
    && echo $'service sshd start\neval `ssh-agent -s`\nssh-add $HOME/.ssh/dev.key' > $HOME/.sshrc

ONBUILD WORKDIR /home/mruby/code
