# MIT License
#
# Copyright (c) 2017 appPlant
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation tasks (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

FROM centos:6
MAINTAINER Sebastian Katzer "katzer@appplant.de"

RUN    yum -y update \
    && yum -y install epel-release centos-release-scl \
    && yum -y groupinstall "Development Tools" \
    && yum -y install libgcc glibc-devel libgcc.i686 glibc-devel.i686 \
    && yum -y install devtoolset-4-gcc devtoolset-4-binutils devtoolset-4-gcc-c++ \
    && yum -y install clang clang-devel \
    && yum -y install cmake curl tar \
    && yum -y clean all
ENV PATH /opt/rh/devtoolset-4/root/usr/bin:$PATH

RUN mkdir -p /opt/ruby-2.2.3/ && \
    curl -s https://s3.amazonaws.com/pkgr-buildpack-ruby/current/centos-6/ruby-2.2.3.tgz | tar xzC /opt/ruby-2.2.3/
ENV PATH /opt/ruby-2.2.3/bin:$PATH
RUN echo "gem: --no-document" > ~/.gemrc && \
    gem install rake bundler --force

ONBUILD WORKDIR /home/mruby/code
ONBUILD ENV GEM_HOME /home/mruby/.gem

ONBUILD ENV PATH $GEM_HOME/bin:$PATH
ONBUILD ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib/
