# MIT License
#
# Copyright (c) 2017 appPlant
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation tasks (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

FROM ubuntu:18.04
MAINTAINER Sebastian Katzer "katzer@appplant.de"

RUN apt-get update && apt-get install -y --no-install-recommends \
    automake \
    bison \
    build-essential \
    ca-certificates \
    clang \
    curl \
    g++-multilib \
    gcc-multilib \
    git \
    libtool \
    llvm-dev \
    make \
    mingw-w64 \
    mingw-w64-tools \
    musl musl-dev musl-tools \
    sed \
    tar \
    vim

# ruby
RUN apt-get install -y ruby
# RUN mkdir -p /opt/ruby-2.5.1/ && \
#     curl -s https://s3-external-1.amazonaws.com/heroku-buildpack-ruby/cedar-14/ruby-2.5.1.tgz | tar xzC /opt/ruby-2.5.1/
# ENV PATH /opt/ruby-2.5.1/bin:$PATH
RUN echo "gem: --no-document" > ~/.gemrc && \
    gem install rake bundler --force

# osx cross compiling tools
RUN cd /opt/ && git clone -q https://github.com/tpoechtrager/osxcross.git
COPY MacOSX10.11.sdk.tar.xz /opt/osxcross/tarballs/
RUN echo "\n" | bash /opt/osxcross/build.sh
RUN rm /opt/osxcross/tarballs/*
ENV PATH /opt/osxcross/target/bin:$PATH

ONBUILD WORKDIR /home/mruby/code
ONBUILD ENV GEM_HOME /home/mruby/.gem

ONBUILD ENV PATH $GEM_HOME/bin:$PATH
ONBUILD ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib/
